/* Lógico_1: */

CREATE TABLE CLIENTE (
    ID_CLIENTE INTEGER PRIMARY KEY,
    ID_LOGIN INTEGER,
    NOME VARCHAR(50),
    E-MAIL VARCHAR,
    ENDERECO VARCHAR,
    SN_ATIVO BOOLEAN,
    TELEFONE INTEGER,
    CELULAR VARCHAR,
    UNIQUE (NOME, E-MAIL)
);

CREATE TABLE COMANDA (
    ID_COMANDA INTEGER PRIMARY KEY,
    ID_COMANDA_PRODUTO INTEGER,
    ID_CLIENTE INTEGER,
    ID_FUNCIONARIO INTEGER,
    TP_PAGAMENTO INTEGER,
    ID_MESA INTEGER,
    VALOR_TOTAL DECIMAL,
    PORCENTAGEM_GARCOM BOOLEAN,
    QR_CODE VARCHAR,
    SN_PAGO INTEGER,
    OBSERVACAO VARCHAR,
    DT_HR_INICIO_COMANDA DATE,
    DT_HR_FIM_COMANDA DATE
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INTEGER PRIMARY KEY,
    ID_FORNECEDOR INTEGER,
    VALOR DECIMAL,
    CODIGO_BARRA VARCHAR,
    TIPO VARCHAR,
    QUANTIDADE INTEGER,
    VALIDADE DATE
);

CREATE TABLE COMANDA_PRODUTO (
    ID_COMANDA_PRODUTO INTEGER PRIMARY KEY,
    ID_COMANDA_FK INTEGER,
    ID_PRODUTO_FK INTEGER
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INTEGER,
    ID_LOGIN INTEGER,
    NOME VARCHAR,
    CPF VARCHAR,
    TELEFONE VARCHAR,
    SETOR INTEGER,
    LOGIN VARCHAR,
    SENHA VARCHAR,
    PRIMARY KEY (ID_FUNCIONARIO, NOME)
);

CREATE TABLE TIPO_PAGAMENTO (
    ID_TP_PAGAMENTO INTEGER PRIMARY KEY,
    DESCRICAO VARCHAR,
    SN_ATIVO BOOLEAN
);

CREATE TABLE FORNECEDOR (
    ID_FORNECEDOR INTEGER PRIMARY KEY,
    CNPJ VARCHAR UNIQUE,
    RAZAO_SOCIAL VARCHAR,
    TP_FORNECIMENTO VARCHAR
);

CREATE TABLE LOGIN (
    ID_LOGIN INTEGER PRIMARY KEY,
    CD_LOGIN VARCHAR,
    CD_SENHA VARCHAR,
    SN_ATIVO BOOLEAN,
    TP_LOGIN VARCHAR
);

CREATE TABLE MESAS (
    ID_MESA INTEGER PRIMARY KEY,
    DESCRICAO VARCHAR,
    SN_ATIVO BOOLEAN
);
 
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_3
    FOREIGN KEY (ID_LOGIN)
    REFERENCES LOGIN (ID_LOGIN);
 
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_4
    FOREIGN KEY (TELEFONE)
    REFERENCES LOGIN (ID_LOGIN);
 
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_2
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);
 
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_3
    FOREIGN KEY (ID_FUNCIONARIO, ???)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO, ???);
 
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_4
    FOREIGN KEY (TP_PAGAMENTO)
    REFERENCES TIPO_PAGAMENTO (ID_TP_PAGAMENTO);
 
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_5
    FOREIGN KEY (ID_COMANDA_PRODUTO)
    REFERENCES COMANDA_PRODUTO (ID_COMANDA_PRODUTO);
 
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_6
    FOREIGN KEY (ID_MESA)
    REFERENCES MESAS (ID_MESA);
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (ID_FORNECEDOR)
    REFERENCES FORNECEDOR (ID_FORNECEDOR);
 
ALTER TABLE COMANDA_PRODUTO ADD CONSTRAINT FK_COMANDA_PRODUTO_2
    FOREIGN KEY (ID_COMANDA_FK)
    REFERENCES COMANDA (ID_COMANDA);
 
ALTER TABLE COMANDA_PRODUTO ADD CONSTRAINT FK_COMANDA_PRODUTO_3
    FOREIGN KEY (ID_PRODUTO_FK)
    REFERENCES PRODUTOS (ID_PRODUTO);
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_2
    FOREIGN KEY (SETOR???, ID_LOGIN???)
    REFERENCES LOGIN (???, ???);