SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE `CLIENTE`, `COMANDA`, `COMANDA_PRODUTO`, `ESTOQUE`, `FORNECEDOR`, `FUNCIONARIO`, `LOGIN`, `MESAS`, `PRODUTOS`, `PRODUTO_ESTOQUE`, `TIPO_PAGAMENTO`;
SET FOREIGN_KEY_CHECKS = 1;


