SELECT  MESAS.DESCRICAO,CLIENTE.NOME,PRODUTOS.NOME_PRODUTO,COUNT(PRODUTOS.NOME_PRODUTO) AS QUANTIDADE,SUM(PRODUTOS.VALOR) AS 'VALOR TOTAL' FROM COMANDA_PRODUTO 
JOIN PRODUTOS ON PRODUTOS.ID_PRODUTO = ID_PRODUTO_FK
JOIN COMANDA  ON COMANDA.ID_COMANDA = COMANDA_PRODUTO.ID_COMANDA_FK 
JOIN MESAS ON COMANDA.ID_MESA = MESAS.ID_MESA
JOIN CLIENTE ON COMANDA.ID_CLIENTE = CLIENTE.ID_CLIENTE
WHERE COMANDA_PRODUTO.ID_COMANDA_FK = 27
GROUP BY PRODUTOS.NOME_PRODUTO