SELECT PRODUTOS.NOME_PRODUTO,COUNT(PRODUTOS.NOME_PRODUTO),sum(PRODUTOS.VALOR) FROM COMANDA_PRODUTO JOIN PRODUTOS
ON PRODUTOS.ID_PRODUTO = ID_PRODUTO_FK
WHERE COMANDA_PRODUTO.ID_COMANDA_FK = 22
GROUP BY PRODUTOS.NOME_PRODUTO